<a href="https://colab.research.google.com/github/xush4/2019SpringCS135ML/blob/master/Example_HW0_Eulidean_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np;

Suppose we have a vector **a**, we want to find the kth nearest neighbors of **a** from a set **S**. We outline the procedure.

In [11]:
a=np.array([1,0,0,0,0])
S=np.identity(6)[:, :5]
print("Suppose a=", a, "and \n\n S has 6 vectors \n", S)

Suppose a= [1 0 0 0 0] and 

 S has 5 vectors 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


We look at the shape of S:

In [16]:
num_row, num_col =S.shape
print("S has ", num_row,  " rows and ", num_col, " columns.")

S has  6  rows and  5  columns.


Now let's loop over S to calculate the distance:
Remember the Euclidean distance of 2 vecctors $a=[a_1,a_2,..., a_n]$, $b=[b_1, b_2, .., b_n]$ is: $\sqrt{\sum_{k=1}^n {(b_k-a_k)^2}}$, which can be also understood as **the length (norm) of $d=b-a$**, i.e. $\sqrt{\sum_{k=1}^n {d_k^2}}$.

In [37]:
dist0=np.zeros(num_row)
dist1=np.zeros(num_row)
dist2=np.zeros(num_row)
for r in range(num_row):
  # Calcualte "dis=a-b"
  d=S[r]-a;

  #get length:
  for i in range(dif.size):
    dist0[r]=np.power(d[i],2)+dist0[r];
  dist0[r]=np.sqrt(dist0[r])

  dist1[r]=np.linalg.norm(dif);

  dist2[r]=np.sqrt(np.dot(dif,dif));
print(dist0)
print(dist1)
print(dist2)


[0.         1.41421356 1.41421356 1.41421356 1.41421356 1.        ]
[0.         1.41421356 1.41421356 1.41421356 1.41421356 1.        ]
[0.         1.41421356 1.41421356 1.41421356 1.41421356 1.        ]


We see all methods give the same (correct) result: 
Let's see what's going on: \\
* dist0 does $\sqrt{\sum_{k=1}^n {d_k^2}}$=$\sqrt{\sum_{k=1}^n {(b_k-a_k)^2}}$. 

* dist1 calculates length (norm) of d using built-in function norm.

* dist2 calculates length (norm) of d using square root of dot product of d and itself.

We recommend everyone understands **dist1** and **dist2** for a much faster computaion in the future. 

The next step includes a sorting process. Let's use dist1 as an example:

In [48]:
index_sorted=np.argsort(dist1)
print(index_sorted)

[0 5 1 2 3 4]


This produces a sorted index according to the array's arg, which in our case is the distance. The result gives the following info:
* The 0th row in **S** is the closest array to **a**. 

* The 5th row is the second.

* 1-4 has the same distance. So we keep the same order.

Suppose we need k nearest neighbor, we get the index of rows by index_sorted[:k] and then call those index in S.

In [54]:
index_1nn=index_sorted[:1] # The nearest
print("Top 1: \n", S[index_1nn])

Top 1: 
 [[1. 0. 0. 0. 0.]]


In [55]:
print("Top 3: \n", S[index_sorted[:3]]) # 3 nearest

Top 3: 
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [56]:
print("Top 5: \n", S[index_sorted[:5]]) # 4 nearest

Top 5: 
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
